server:
  port: 9999

spring:
  application:
    name: authorization-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/oauth?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 3600ms

security:
  oauth2:
    resource:
      filter-order: 99